export const cuisineList = [
    "Italian",
    "Chinese",
    "Japanese",
    "Indian",
    "Pakistani",
    "French",
    "Mexican",
    "Thai",
    "Spanish",
    "Greek",
    "Turkish",
    "Lebanese",
    "Vietnamese",
    "Tibetan",
    "Korean",
    "Moroccan",
    "Ethiopian",
    "Brazilian",
    "Indonesian",
    "Malaysian",
    "Filipino",
    "Cuban",
    "Cajun",
    "Jamaican",
    "Russian",
    "Ukrainian",
    "German",
    "Hungarian",
    "Czech",
    "Swiss",
    "Portuguese",
    "Belgian",
    "Dutch",
    "Swedish",
    "Danish",
    "Norwegian",
    "Finnish",
    "Saudi Arabian",
    "South African",
    "Egyptian",
    "Australian",
    "New Zealand",
    "Caribbean",
    "Sri Lankan",
];
